name: Publish to staging

on:
   push:
      branches-ignore:
         - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
        - uses: actions/checkout@v6
        - name: Setup .npmrc file to install from GitHub Packages
          run: |
            echo "@lb-01:registry=https://npm.pkg.github.com" >> ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
        - run: npm ci
        - run: npm run build --if-present         
        - name: Deploy staging 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
              token: ${{ secrets.GITHUB_TOKEN }}
              branch: gh-pages
              folder: dist
              clean: true